apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vw939elxx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vw939elxx-go 
  name: vw939elxx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vw939elxx-go 
